---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: ${aws-controller-config}
  annotations:
    eks.amazonaws.com/role-arn: ${iam-role-arn}
spec:
  podSecurityContext:
    fsGroup: 2000
  args:
    - --debug
