autoDiscovery:
  clusterName: ${eks_cluster_id}

awsRegion: ${aws_region}

cloudProvider: aws

extraArgs:
  logtostderr: true
  stderrthreshold: info
  v: 4
  aws-use-static-instance-list: true

nodeSelector:
  NodeGroupType: ${node_group_type}
  kubernetes.io/os: ${operating_system}

rbac:
  create: true
  pspEnabled: false
  serviceAccount:
    create: false

# replicaCount -- Desired number of pods
replicaCount: 1

# Best practice to update the resource requests and limits for each add-on
resources:
   limits:
     cpu: 1000m
     memory: 1G
   requests:
     cpu: 200m
     memory: 512Mi

# Best practice to updateStrategy for each add-on
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 1
