apiVersion: v1
kind: Service
metadata:
  name: katib-ui
  namespace: kubeflow
  labels:
    katib.kubeflow.org/component: ui
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      name: ui
      targetPort: 8080
  selector:
    katib.kubeflow.org/component: ui
