apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
  - ../katib-standalone
  # rbac for leader-election
  - leader-election-rbac.yaml
replicas:
  - name: katib-controller
    count: 2
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: katib-controller
    path: ./patches/controller.yaml
