serviceAccounts:
  server:
    name: ${service_account_name}
    annotations: 
        eks.amazonaws.com/role-arn: ${ingest_role_arn}
server:
  remoteWrite:
    - url: ${amp_workspace_url}
      sigv4:
        region: ${aws_region}
      queue_config:
        max_samples_per_send: 1000
        max_shards: 200
        capacity: 2500
  
