
# This service can be accessed using LB DNS e.g., http://<LB DNS name>>:8000/

---
apiVersion: v1
kind: Service
metadata:
  name: on-demand-greeting-service
  namespace: default
spec:
  selector:
    app: on-demand-greeting-pod
  ports:
    - name: web
      port: 8000
      targetPort: 8080
  #type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: on-demand-greeting
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: on-demand-greeting-pod
  template:
    metadata:
      labels:
        app: on-demand-greeting-pod
    spec:
      #      tolerations:
      #        - key: "spotInstance"
      #          # operator: "Exists"
      #          value: "true"
      #          effect: "PreferNoSchedule"
      containers:
        - name: hello-kubernetes
          image: paulbouwer/hello-kubernetes:1.9
          ports:
            - containerPort: 8080
          env:
            - name: MESSAGE
              value: I just deployed this on EKS!
      nodeSelector:
        eks.amazonaws.com/capacityType: ON_DEMAND

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: on-demand-greeting-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: on-demand-greeting-service
                port:
                  number: 8000

