apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- service.yaml
- statefulset.yaml
- envoy-filter.yaml
- pvc.yaml

namespace: istio-system

configMapGenerator:
- name: oidc-authservice-parameters
  envs:
  - params.env

secretGenerator:
- name: oidc-authservice-client
  type: Opaque
  envs:
  - secret_params.env

generatorOptions:
  disableNameSuffixHash: true

vars:
- name: AUTHSERVICE_NAMESPACE
  objref:
    kind: Service
    name: authservice
    apiVersion: v1
  fieldref:
    fieldpath: metadata.namespace
- name: AUTHSERVICE_SERVICE
  objref:
    kind: Service
    name: authservice
    apiVersion: v1
  fieldref:
    fieldpath: metadata.name
configurations:
- params.yaml
images:
- name: gcr.io/arrikto/kubeflow/oidc-authservice
  newName: gcr.io/arrikto/kubeflow/oidc-authservice
  newTag: 28c59ef
