apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- upstream/serving-core.yaml
- upstream/net-istio.yaml
- istio-authorization-policy.yaml
patchesStrategicMerge:
- patches/configmap-patch.yaml
- patches/namespace-injection.yaml
- patches/clusterrole-patch.yaml
- patches/service-labels.yaml
patches:
- path: patches/sidecar-injection.yaml
  target:
    kind: Deployment
