# KubeCost WebUI -> kubectl port-forward --namespace kubecost deployment/kubecost-cost-analyzer 9090

global:
  # Free use token available at https://www.kubecost.com/install#show-instructions
  kubecostToken: "YmVuY2FzaWVAYW1hem9uLmNvbQ==xm343yadf98"
  # pricingCsv:
  #   enabled: false
  #   location:
  #     provider: "AWS"
  #     region: "us-east-1"
  #     URI: s3://kc-csv-test/pricing_schema.csv # a valid file URI
  #     csvAccessCredentials: pricing-schema-access-secret

  # This Prometheus setup is reusing the existing Prometheus deployment
  # Check for more docs under https://guide.kubecost.com/hc/en-us/articles/4407595941015
  prometheus:
    fqdn: http://kube-prometheus-stack-prometheus.kube-prometheus-stack.svc:9090
    enabled: false

# If you have node-exporter and/or KSM running on your cluster, follow this step to disable the Kubecost included versions.
prometheus:
  nodeExporter:
    enabled: false
  serviceAccounts:
    nodeExporter:
      create: false
  kubeStateMetrics:
    enabled: false

#imageVersion: prod-1.96.0 # commented to use the latest

kubecostFrontend:
  image: public.ecr.aws/kubecost/frontend
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"

kubecostMetrics:
  emitPodAnnotations: true
  emitNamespaceAnnotations: true

kubecostModel:
  image: public.ecr.aws/kubecost/cost-model
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"

# Set this to false if you're bringing your own service account.
#serviceAccount:
#  create: false
#  name: kubecost-cost-analyzer
#  annotations:
#    eks.amazonaws.com/role-arn: <iam-role-arn>

# Define persistence volume for cost-analyzer
persistentVolume:
  size: 32Gi
  dbSize: 32.0Gi
  enabled: true # Note that setting this to false means configurations will be wiped out on pod restart.
  storageClass: auto-ebs-sc
  # existingClaim: kubecost-cost-analyzer # a claim in the same namespace as kubecost
