apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eks:addon-manager
  namespace: opentelemetry-operator-system
subjects:
- kind: User
  name: eks:addon-manager
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: eks:addon-manager
  apiGroup: rbac.authorization.k8s.io
