global:
  ## Override the deployment namespace
  namespaceOverride: logging

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  name: ${service_account_name}

cloudWatch:
  enabled: false
  region: ${aws_region}
firehose:
  enabled: false
  region: ${aws_region}
kinesis:
  enabled: false
  region: ${aws_region}
elasticsearch:
  enabled: false
  region: ${aws_region}

service:
  extraService: |
    Flush                     5
    Log_Level                 info
    Daemon                    off
    HTTP_Server               $${HTTP_SERVER}
    HTTP_Listen               0.0.0.0
    HTTP_Port                 $${HTTP_PORT}
    storage.path              /var/lib/fluentbit/state/flb-storage/
    storage.sync              normal
    storage.checksum          off
    storage.backlog.mem_limit 5M

  parsersFiles:
    - /fluent-bit/parsers/parsers.conf
  extraParsers: |
    [PARSER]
        Name                syslog
        Format              regex
        Regex               ^(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
        Time_Key            time
        Time_Format         %b %d %H:%M:%S

    [PARSER]
        Name                vpccni
        Format              json
        Time_Key            ts
        Time_Format         %Y-%m-%dT%H:%M:%S.%LZ


input:
  tag: "application.*"
  path: "/var/log/containers/*.log"
  db: "/var/lib/fluentbit/state/flb_container.db"
  parser: docker
  dockerMode: "On"
  memBufLimit: 50MB
  skipLongLines: "On"
  refreshInterval: 10
  extraInputs: |
    Exclude_Path        /var/log/containers/aws-for-fluent-bit*, /var/log/containers/aws-node*, /var/log/containers/kube-proxy*
    Docker_Mode_Flush   5
    Rotate_Wait         30
    storage.type        filesystem
    Read_from_Head      $${READ_FROM_HEAD}

additionalInputs: |
  [INPUT]
      Name                tail
      Tag                 application.*
      Path                /var/log/containers/aws-for-fluent-bit*
      Parser              docker
      DB                  /var/lib/fluentbit/state/flb_log.db
      Mem_Buf_Limit       5MB
      Skip_Long_Lines     On
      Refresh_Interval    10
      Read_from_Head      $${READ_FROM_HEAD}

  [INPUT]
      Name                systemd
      Tag                 dataplane.systemd.*
      Systemd_Filter      _SYSTEMD_UNIT=docker.service
      Systemd_Filter      _SYSTEMD_UNIT=containerd.service
      Systemd_Filter      _SYSTEMD_UNIT=kubelet.service
      DB                  /var/lib/fluentbit/state/systemd.db
      Path                /var/log/journal
      Read_From_Tail      $${READ_FROM_TAIL}

  [INPUT]
      Name                tail
      Tag                 dataplane.tail.*
      Path                /var/log/containers/aws-node*, /var/log/containers/kube-proxy*
      Docker_Mode         On
      Docker_Mode_Flush   5
      Parser              docker
      DB                  /var/lib/fluentbit/state/flb_dataplane_tail.db
      Mem_Buf_Limit       50MB
      Skip_Long_Lines     On
      Refresh_Interval    10
      Rotate_Wait         30
      storage.type        filesystem
      Read_from_Head      $${READ_FROM_HEAD}

  [INPUT]
      Name                tail
      Tag                 dataplane.tail.*
      Path                /var/log/aws-routed-eni/ipamd*, /var/log/aws-routed-eni/plugin*
      Docker_Mode         On
      Docker_Mode_Flush   5
      Parser              vpccni
      DB                  /var/lib/fluentbit/state/flb_dataplane_tail.db
      Mem_Buf_Limit       50MB
      Skip_Long_Lines     On
      Refresh_Interval    10
      Rotate_Wait         30
      storage.type        filesystem
      Read_from_Head      $${READ_FROM_HEAD}

  [INPUT]
      Name                tail
      Tag                 host.dmesg
      Path                /var/log/dmesg
      Parser              syslog
      DB                  /var/lib/fluentbit/state/flb_dmesg.db
      Mem_Buf_Limit       5MB
      Skip_Long_Lines     On
      Refresh_Interval    10
      Read_from_Head      $${READ_FROM_HEAD}

  [INPUT]
      Name                tail
      Tag                 host.messages
      Path                /var/log/messages
      Parser              syslog
      DB                  /var/lib/fluentbit/state/flb_messages.db
      Mem_Buf_Limit       5MB
      Skip_Long_Lines     On
      Refresh_Interval    10
      Read_from_Head      $${READ_FROM_HEAD}

  [INPUT]
      Name                tail
      Tag                 host.secure
      Path                /var/log/secure
      Parser              syslog
      DB                  /var/lib/fluentbit/state/flb_secure.db
      Mem_Buf_Limit       5MB
      Skip_Long_Lines     On
      Refresh_Interval    10
      Read_from_Head      $${READ_FROM_HEAD}


filter:
  match: "application.*"
  kubeURL: "https://kubernetes.default.svc.cluster.local:443"
  mergeLog: "On"
  mergeLogKey: "log_processed"
  keepLog: "On"
  k8sLoggingParser: "On"
  k8sLoggingExclude: "Off"
  extraFilters: |
    Kube_Tag_Prefix     application.var.log.containers.
    Labels              Off
    Annotations         Off

additionalFilters: |
  [FILTER]
      Name                modify
      Match               dataplane.systemd.*
      Rename              _HOSTNAME                   hostname
      Rename              _SYSTEMD_UNIT               systemd_unit
      Rename              MESSAGE                     message
      Remove_regex        ^((?!hostname|systemd_unit|message).)*$

  [FILTER]
      Name                aws
      Match               dataplane.*
      imds_version        v2

  [FILTER]
      Name                aws
      Match               host.*
      imds_version        v2


additionalOutputs: |
  [OUTPUT]
      Name                cloudwatch_logs
      Match               application.*
      region              ${aws_region}
      log_group_name      ${log_group_name}
      log_stream_prefix   $${HOST_NAME}-
      auto_create_group   true
      extra_user_agent    container-insights

  [OUTPUT]
      Name                cloudwatch_logs
      Match               dataplane.*
      region              ${aws_region}
      log_group_name      ${dataplane_log_group}
      log_stream_prefix   $${HOST_NAME}-
      auto_create_group   true
      extra_user_agent    container-insights

  [OUTPUT]
      Name                cloudwatch_logs
      Match               host.*
      region              ${aws_region}
      log_group_name      ${host_log_group}
      log_stream_prefix   $${HOST_NAME}.
      auto_create_group   true
      extra_user_agent    container-insights


resources:
  limits:
    memory: 250Mi
  requests:
    cpu: 50m
    memory: 100Mi

## Assign a PriorityClassName to pods if set
# priorityClassName: system-node-critical

updateStrategy:
  type: RollingUpdate

nodeSelector:
  kubernetes.io/os: linux

affinity: { }

annotations: { }
# iam.amazonaws.com/role: arn:aws:iam::123456789012:role/role-for-fluent-bit

env:
  - name: AWS_REGION
    value: ${aws_region}
  - name: CLUSTER_NAME
    value: ${cluster_name}
  - name: HOST_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName
  - name: READ_FROM_HEAD
    value: "Off"
  - name: READ_FROM_TAIL
    value: "On"
  - name: HTTP_SERVER
    value: "On"
  - name: HTTP_PORT
    value: "2020"

volumes:
  - name: varlog
    hostPath:
      path: /var/log
  - name: varlibdockercontainers
    hostPath:
      path: /var/lib/docker/containers
  - name: varlibfluentbit
    hostPath:
      path: /var/lib/fluentbit

volumeMounts:
  - name: varlog
    mountPath: /var/log
    readOnly: true
  - name: varlibdockercontainers
    mountPath: /var/lib/docker/containers
    readOnly: true
  - name: varlibfluentbit
    mountPath: /var/lib/fluentbit
