apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "provisioner.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ template "provisioner.chart" . }}
    app.kubernetes.io/name: {{ template "provisioner.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
{{- if .Values.daemonset.nodeLabels }}
  nodeLabelsForPV: |
   {{- range $label := .Values.daemonset.nodeLabels }}
    - {{$label}}
   {{- end }}
{{- end }}
{{- if .Values.common.labelsForPV }}
  labelsForPV: |
   {{- range $label, $value := .Values.common.labelsForPV }}
    {{$label}} : {{$value}}
   {{- end }}
{{- end }}
{{- if .Values.common.useAlphaAPI }}
  useAlphaAPI: "true"
{{- end }}
{{- if .Values.common.setPVOwnerRef }}
  setPVOwnerRef: "true"
{{- end }}
{{- if .Values.common.useJobForCleaning }}
  useJobForCleaning: "yes"
{{- end}}
{{- if .Values.common.useNodeNameOnly }}
  useNodeNameOnly: "true"
{{- end }}
{{- if .Values.common.minResyncPeriod }}
  minResyncPeriod: {{ .Values.common.minResyncPeriod | quote }}
{{- end}}
  storageClassMap: |
    {{- range $classConfig := .Values.classes }}
    {{ $classConfig.name }}:
      hostDir: {{ $classConfig.hostDir }}
      mountDir: {{ $classConfig.mountDir | default $classConfig.hostDir }}
      {{- if $classConfig.blockCleanerCommand }}
      blockCleanerCommand:
      {{- range $val := $classConfig.blockCleanerCommand }}
        - {{ $val | quote }}
      {{- end}}
      {{- end }}
      {{- if $classConfig.volumeMode }}
      volumeMode: {{ $classConfig.volumeMode }}
      {{- end }}
      {{- if $classConfig.fsType }}
      fsType: {{ $classConfig.fsType }}
      {{- end }}
      {{- if $classConfig.namePattern }}
      namePattern: {{ $classConfig.namePattern | quote }}
      {{- end }}
    {{- end }}
