# Default values for nops-k8s-agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: ghcr.io/nops-io/nops-k8s-agent
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "deploy"



ingress:
  enabled: false



service:
  type: ClusterIP
  port: 80



serviceAccount:
  create: false



cronjob:
  schedule: "*/10 * * * *"
  schedule_low: "0 * * * *"
  schedule_medium: "*/30 * * * *"
  schedule_high: "*/10 * * * *"



env_variables:
  APP_ENV: "live"
  APP_PROMETHEUS_SERVER_ENDPOINT: ${app_prometheus_server_endpoint}
  APP_NOPS_K8S_AGENT_TIMEOUT: "120"
  APP_NOPS_K8S_AGENT_CLUSTER_ID: ${app_nops_k8s_agent_clusterid}
  APP_NOPS_K8S_COLLECTOR_HOST : "app.nops.io"
  APP_NOPS_K8S_COLLECTOR_PORT: "443"
  APP_NOPS_K8S_COLLECTOR_NO_SSL: "1"
  APP_NOPS_K8S_COLLECTOR_SKIP_SSL_VALIDATION: ${app_nops_k8s_collector_skip_ssl}
  APP_NOPS_K8S_COLLECTOR_API_KEY: ${app_nops_k8s_collector_api_key}
  APP_NOPS_K8S_COLLECTOR_AWS_ACCOUNT_NUMBER: ${app_nops_k8s_collector_aws_account_number}
  APP_NOPS_K8S_AGENT_PROM_TOKEN: ${app_nops_k8s_agent_prom_token}