name: e2e-test

on:
  workflow_dispatch:

jobs:
    deploy:
      name: Run e2e test
      runs-on: ubuntu-latest

      # These permissions are needed to interact with GitHub's OIDC Token endpoint.
      permissions:
        id-token: write
        contents: read

      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Configure AWS credentials from Test account
          uses: aws-actions/configure-aws-credentials@v1
          with:
            role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
            aws-region: us-west-2
            role-duration-seconds: 1800
            role-session-name: GithubActions-Session

        - name: Terraform Job
          uses: hashicorp/setup-terraform@v1
          with:
            terraform_version: 1.0.11

        - name: Terraform Fmt
          id: fmt
          run: terraform fmt -check -recursive -list -no-color
          continue-on-error: false

        - name: Terraform Init
          id: init
          run: terraform init
          working-directory: test/e2e/eks
          continue-on-error: false

        - name: Terraform Validate
          id: validate
          working-directory: test/e2e/eks
          run: terraform validate -no-color
          continue-on-error: false

        - name: Terraform Plan
          id: plan
          working-directory: test/e2e/eks
          run: terraform plan -no-color
          continue-on-error: false

        - name: Terraform Apply
          id: apply
          working-directory: test/e2e/eks
          run: terraform apply -no-color -auto-approve
          continue-on-error: true

        - name: Terraform Destroy
          if: steps.apply.outcome == 'success' || steps.apply.outcome == 'failure'
          id: destroy
          working-directory: test/e2e/eks
          run: terraform destroy -no-color -auto-approve
          continue-on-error: false

        - name: Fail if TF apply failed
          if: steps.apply.outcome == 'failure'
          id: fail-if-tf-apply-failed
          run: |
            echo "Terraform Apply step failed...Please check the logs of the Terraform Apply step."
            echo "Failing the job to avoid false positives."
            exit 1
          continue-on-error: false