name: e2e-all-examples-parallel

on:
  workflow_dispatch:
    inputs:
      TFDestroy:
        description: "Destroy TF Automatically (false/true) - Default: true"
        required: true
        default: "true"

jobs:
  deploy:
    name: E2E Example
    runs-on: ubuntu-latest

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        tf_working_dir:
          [
            examples/advanced/k8s_addons,
            examples/advanced/live,
            examples/analytics/emr-on-eks,
            examples/analytics/spark-k8s-operator,
            examples/argocd,
            examples/aws-efs-csi-driver,
            examples/ci-cd,
            examples/crossplane,
            examples/eks-cluster-with-new-vpc,
            examples/eks-managed-addons,
            examples/fargate-profiles,
            examples/fully-private-eks-cluster,
            examples/game-tech/agones-game-controller,
            examples/ingress-controllers,
            examples/karpenter,
            examples/managed-node-groups,
            examples/multi-tenancy-with-teams,
            examples/observability,
            examples/self-managed-node-groups,
            examples/windows-node-groups
          ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: us-west-2
          role-duration-seconds: 3600
          role-session-name: GithubActions-Session

      - name: Terraform Job
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.11

      - name: Terraform Fmt
        id: fmt
        run: terraform fmt -check -recursive -list -no-color
        continue-on-error: false

      - name: Terraform Init
        id: init
        run: terraform init -reconfigure
        working-directory: ${{ matrix.tf_working_dir }}
        continue-on-error: false

      - name: Terraform Validate
        id: validate
        working-directory: ${{ matrix.tf_working_dir }}
        run: terraform validate -no-color
        continue-on-error: false

      - name: Terraform Plan
        id: plan
        working-directory: ${{ matrix.tf_working_dir }}
        run: terraform plan -no-color
        continue-on-error: false
