---
name: super-lint
on:
  pull_request:

jobs:
  superlinter:
    name: super-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint Code
        uses: github/super-linter@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: "main"
          DISABLE_ERRORS: false
          VALIDATE_BASH: true
          VALIDATE_JSON: true
          VALIDATE_MD: true
          VALIDATE_TERRAFORM: true
          VALIDATE_YAML: true

